http:
  request:
    #从连接池中获取到连接的最长时间
    connectionRequestTimeout: 500
    #创建连接的最长时间
    connectTimeout: 50000
    #数据传输的最长时间
    socketTimeout: 30000
    #提交请求前测试连接是否可用
    staleConnectionCheckEnabled: true


  pool:
    #设置连接总数
   maxTotal: 200
   #设置每个地址的并发数
   defaultMaxPerRoute: 100